import vm from "node:vm";
import { describe, expect, it } from "vitest";
import { renderBoundaryWorkbench } from "./boundary-workbench.js";

describe("Auto Boundary Workbench renderer", () => {
  it("emits executable browser JavaScript and the host-neutral guided journey", () => {
    const html = renderBoundaryWorkbench("test-csrf");
    const script = html.match(/<script>([\s\S]*?)<\/script>/)?.[1];

    expect(script).toBeTruthy();
    expect(() => new vm.Script(script!, { filename: "boundary-workbench.js" })).not.toThrow();
    expect(html).toContain("Synapsor is creating the small set of database powers your agent may use.");
    expect(html).toContain("Writes create proposals and cannot be approved or applied by the model.");
    expect(html).toContain("The model also cannot activate new authority.");
    expect(html).toContain("Advanced permissions");
    expect(html).toContain("Review security exceptions");
    expect(html).toContain("includedIds.has(relation.target_resource)");
    expect(html).toContain("includedIds.has(link.source_resource)&&includedIds.has(link.target_resource)");
    expect(html).toContain("Exact database role posture");
    expect(html).toContain("Analyze reviewed data");
    expect(html).toContain("Ask with your model");
    expect(html).toContain("Synapsor does not relay the request.");
    expect(html).toContain("Activation, approval, apply, worker control, and notification control remain outside this surface.");
    expect(html).toContain("Session-only conversation");
    expect(html).toContain('id="ask-key" type="password"');
    expect(html).toContain('maxlength="4000"');
    expect(html).toContain('post("/api/ask/run",{question})');
    expect(html).not.toMatch(/localStorage|sessionStorage|indexedDB/);
    expect(html).toContain("Optional filter");
    expect(html).toContain('id="aggregate-dimension-2"');
    expect(html).toContain('id="aggregate-dimension-3"');
    expect(html).toContain("Choose each reviewed grouping field only once.");
    expect(html).toContain("One record");
    expect(html).toContain("Make this analysis reusable");
    expect(html).toContain("preferredProtectQueryRef=result.protect?.token||null");
    expect(html).toContain("query.query_ref===preferredRef");
    expect(html).toContain("Add safe action");
    expect(html).toContain("Bounded JSON for developers");
    expect(html).toContain("resultColumnLabel");
    expect(html).toContain("Trace the role from IdP claim to approval and apply");
    expect(html).toContain("docs/approval-roles-and-operator-identity.md");
    expect(html).toContain("Tool (local authoring only)");
    expect(html).toContain("Finish authoring and review proposal");
    expect(html).not.toMatch(/id="protect-disable-explore" type="checkbox" checked/);
    expect(html).toContain("Generic stdio MCP");
    expect(html).toContain("Managed project installers");
    expect(html).toContain("mcp install cursor");
    expect(html).toContain("mcp install claude-code");
    expect(html).toContain("mcp install vscode");
    expect(html).toContain("Codex");
    expect(html).not.toMatch(/execute_sql|raw SQL tool|approve tool|apply tool/i);
  });
});
