import fs from "node:fs/promises";
import path from "node:path";

const generatedMarker = "<!-- Generated by Synapsor Runner Safe Action Composer. Edit the canonical package source, not host wrappers. -->";

export const safeActionAgentInstructions = `# Synapsor Safe Action authoring

You are editing a disabled, code-first Synapsor Safe Action draft. Your job is
to turn one developer-stated business intent into a narrow canonical capability
and deterministic tests. You may author files and run local validation. You do
not have activation, approval, apply, commit, revert, credential, or trusted
tenant/principal authority.

## Required workflow

1. Inspect existing application schema, ORM, OpenAPI, tests, and the current
   reviewed Synapsor read capability. Do not connect to an unapproved database,
   print environment values, or inspect secrets. Runner records safely detected
   file paths, frameworks, and environment-variable names (never values) in
   \`.synapsor/composer.json\`; treat them as structural suggestions, not authority.
2. Edit only the requested file under \`synapsor/actions/\`. Use the existing
   \`defineCapability\` API from \`@synapsor/runner/authoring\`; do not invent a
   new contract format.
3. Keep tenant, principal, role, source, table, schema, column, predicate,
   approval identity, and credentials out of model-visible arguments.
4. Treat field names and schema heuristics only as suggestions. Keep sensitive,
   unknown, credential, token, private-note, risk, and identity fields out until
   a developer explicitly reviews them.
5. Define one business action, fixed target, bounded arguments, exact allowed
   mutation, conflict/version guard, affected-row/value bounds, explicit
   approval authority, explicit executor mode, and idempotent receipt behavior.
6. Add deterministic positive and negative coverage for operator separation,
   tenant/principal denial, kept-out fields, argument/value bounds, transition
   guards, source unchanged before approval, conflict behavior, and the intended
   business effect where those controls apply.
7. Run the project formatter, then:

   \`synapsor-runner action validate <action.ts> --json\`

   Use the returned canonical draft/test paths to run strict contract lint,
   explain, and contract tests. Fix every error. Warnings must be shown to the
   developer rather than bypassed.
8. Leave the action disabled. Tell the developer to open the secured localhost
   Workbench, run the real staging-data proposal preview, review the exact Data
   PR and digest, and activate it personally.

## Never do these things

- Never activate an action or edit \`.synapsor/active*\`, the active contract
  reference in \`synapsor.runner.json\`, or an activation manifest.
- Never add raw/generic SQL, model-generated predicates, arbitrary identifiers,
  unbounded writes, or model-visible approve/apply/commit/revert tools.
- Never add tenant/principal values as tool arguments or widen trusted scope.
- Never read, write, copy, log, or change database/executor/operator secrets.
- Never infer write permission, sensitive-field visibility, approval policy,
  auto-approval, executor authority, or production credentials.
- Never remove unresolved review placeholders or diagnostics without replacing
  them with developer-reviewed authority grounded in application evidence.
- Never claim success before deterministic validation and tests pass. A valid
  draft is still not active.

When uncertain, fail closed and state the exact unresolved authority question,
where the suggestion came from, and what a developer must decide.
`;

export async function writeSafeActionAgentInstructions(projectRootInput: string): Promise<{
  canonical: string;
  codex: string;
  claude: string;
}> {
  const projectRoot = await fs.realpath(path.resolve(projectRootInput));
  const canonical = path.join(projectRoot, "synapsor", "SAFE_ACTION_AGENT.md");
  const codex = path.join(projectRoot, "synapsor", "actions", "AGENTS.md");
  const claude = path.join(projectRoot, "synapsor", "actions", "CLAUDE.md");
  await writeManaged(canonical, `${generatedMarker}\n\n${safeActionAgentInstructions}`);
  await writeManaged(codex, `${generatedMarker}\n\n${safeActionAgentInstructions}\n\nCanonical project copy: \`../SAFE_ACTION_AGENT.md\`.\n`);
  await writeManaged(claude, `${generatedMarker}\n\n${safeActionAgentInstructions}\n\nCanonical project copy: \`../SAFE_ACTION_AGENT.md\`.\n`);
  return {
    canonical: relative(projectRoot, canonical),
    codex: relative(projectRoot, codex),
    claude: relative(projectRoot, claude),
  };
}

async function writeManaged(filePath: string, value: string): Promise<void> {
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  try {
    const existing = await fs.readFile(filePath, "utf8");
    if (existing === value) return;
    if (!existing.startsWith(generatedMarker)) {
      throw new Error(`Refusing to replace an unowned agent instruction file: ${filePath}`);
    }
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
  }
  const temporary = path.join(path.dirname(filePath), `.${path.basename(filePath)}.${process.pid}.${Math.random().toString(16).slice(2)}.tmp`);
  try {
    await fs.writeFile(temporary, value, { encoding: "utf8", mode: 0o600, flag: "wx" });
    await fs.rename(temporary, filePath);
  } finally {
    await fs.rm(temporary, { force: true }).catch(() => undefined);
  }
}

function relative(root: string, filePath: string): string {
  const value = path.relative(root, filePath).split(path.sep).join("/");
  return value.startsWith(".") ? value : `./${value}`;
}
