services:
  postgres:
    image: postgres:16
    container_name: synapsor_runner_plan_credit
    environment:
      POSTGRES_DB: synapsor_runner_plan_credit
      POSTGRES_USER: synapsor_admin
      POSTGRES_PASSWORD: synapsor_admin_password
    ports:
      - "55438:5432"
    volumes:
      - ./seed:/docker-entrypoint-initdb.d:ro
